apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    # for 3 node cluster change role to ; worker
    machineconfiguration.openshift.io/role: master
  name: sctpmodule
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:,
          mode: 438
          overwrite: true
          path: /etc/modprobe.d/sctp-blacklist.conf
        - contents:
            source: data:text/plain;charset=utf-8,sctp
          mode: 438
          overwrite: true
          path: /etc/modules-load.d/sctp-load.conf
