apiVersion: v1
kind: Service
metadata:
  name: debug-app
  labels:
    name: debug-app
spec:
  selector:
    name: debug-app
  ports:
    - protocol: TCP
      port: 88  
      targetPort: 88
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: debug-app
  name: debug-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: debug-app
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        name: debug-app
    spec:
      containers:
      - image: quay.io/wcaban/net-toolbox:latest
        name: debug-app
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
