# Default values for 5gcore-helm.

open5gcore:
  image:
    repository: docker.io/efatnar/open5gcore
    pullPolicy: IfNotPresent
    tag: "v2.0"
    oldtag: "v1.1"

webui:
  image:
    repository: docker.io/efatnar/open5gcore-webui
    pullPolicy: IfNotPresent
    tag: "v1.1"

k8s:
  interface: eth0
  tuninterface: ogstun
  
cnf:
  dnn: internet
  dnnremote: internet
  amf:
    mcc: 208
    mnc: 93
    tacall: [3, 5, 7, 9]
    taclocal: [7, 9]
    tacremote: [3, 5]
    sctp:
      nodeport: 30412
      port: 38412
    http:
      nodeport: 30080
      port: 80
  upf:
    nodeport: 30423
    nodeportremote: 30425
    
