apiVersion: federation.maistra.io/v1
kind: ImportedServiceSet
metadata:
  name: prod2-mesh
  namespace: prod1-mesh
spec:
  importRules:
  - type: NameSelector
    importAsLocal: false
    nameSelector:
      namespace: 5gcore
      name: "*"
      alias:
         name: "*"-v2
         namespace: prod1-5gcore
