apiVersion: federation.maistra.io/v1
kind: ImportedServiceSet
metadata:
  name: prod2-mesh
  namespace: prod1-mesh
spec:
  importRules:
    - importAsLocal: false
      nameSelector:
        alias:
          name: open5gs-upf-v2
          namespace: prod1-5gcore
        name: open5gs-upf
        namespace: prod2-5gcore
      type: NameSelector
