apiVersion: federation.maistra.io/v1
kind: ImportedServiceSet
metadata:
  name: prod2-mesh
  namespace: prod1-mesh
spec:
  importRules:
    - importAsLocal: false
      nameSelector:
        alias:
          namespace: prod1-5gcore
        namespace: 5gcore
      type: NameSelector
