kind: ServiceMeshPeer
apiVersion: federation.maistra.io/v1
metadata:
  name: prod2-mesh
  namespace: prod1-mesh
spec:
  remote:
    addresses:
    - 172.27.103.88
    discoveryPort: 30188
    servicePort: 30443
  gateways:
    ingress:
      name: prod2-mesh-ingress
    egress:
      name: prod2-mesh-egress
  security:
    trustDomain: prod2-mesh.local
    clientID: prod2-mesh.local/ns/prod2-mesh/sa/prod1-mesh-egress-service-account
    certificateChain:
      kind: ConfigMap
      name: prod2-mesh-ca-root-cert
