kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: open5gs-upf
  namespace: prod1-5gcore
spec:
  hosts:
    - open5gs-upf.prod1-5gcore.svc.cluster.local
  http:
    - route:
        - destination:
            host: open5gs-upf.prod1-5gcore.svc.cluster.local
          weight: 60
        - destination:
            host: open5gs-upf.prod2-5gcore.svc.prod1-mesh-exports.local
          weight: 40
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: open5gs-nrf
  namespace: prod1-5gcore
spec:
  hosts:
    - open5gs-nrf.prod1-5gcore.svc.cluster.local
  http:
    - route:
        - destination:
            host: open5gs-nrf.prod1-5gcore.svc.cluster.local
          weight: 60
        - destination:
            host: open5gs-nrf.prod2-5gcore.svc.prod1-mesh-exports.local
          weight: 40
