kind: ExportedServiceSet
apiVersion: federation.maistra.io/v1
metadata:
  name: prod1-mesh
  namespace: prod2-mesh
spec:
  exportRules:
  - type: LabelSelector
    labelSelector:
      namespace: prod2-5gcore
      selector:
        matchLabels:
          epc-mode: upf
          export-service: "true"
      alias:
        namespace: 5gcore
  - type: LabelSelector
    labelSelector:
      namespace: prod2-5gcore
      selector:
        matchLabels:
          epc-mode: amf
      alias:
        namespace: 5gcore
  - type: LabelSelector
    labelSelector:
      namespace: prod2-5gcore
      selector:
        matchLabels:
          epc-mode: smf
      alias:
        namespace: 5gcore
