apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---    
apiVersion: v1
kind: Pod
metadata:
  name: loki
  labels:
    app: loki
spec:
  volumes:
    - name: loki-store
      persistentVolumeClaim:
        claimName: loki-store
  containers:
    - name: loki
      image: grafana/loki
      volumeMounts:
        - mountPath: "/loki-store"
          name: loki-store
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: network-observability
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
---
kind: Service
apiVersion: v1
metadata:
  name: loki-np
  namespace: network-observability
spec:
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 30100
  type: NodePort
  selector:
    app: loki
